source 'https://github.com/CocoaPods/Specs.git'

target 'LSDHelpers', :exclusive => true do
  pod "LSDHelpers", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LSDHelpers", :path => "../"

  
end
